version: "3.9"
services:
  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper-docker
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka-server-1:
    image: "bitnami/kafka:3.6.0"
    container_name: kafka-container-1
    hostname: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:9093"  
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka-1:9093" 
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181/kafka-1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - kafka_network

  schema-registry:
    image: bitnami/schema-registry:latest
    container_name: schema-registry-docker
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka-1:9093
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      #- {"type": "record","name": "Kisi","fields": [{"name": "id", "type": "string"},{"name": "first_name", "type": "string"},{"name": "last_name", "type": "string"},{"name": "email", "type": "string"},{"name": "gender", "type": "string"},{"name": "ip_address", "type": "string"},{"name": "user_name", "type": "string"},{"name": "agent", "type": "string"},{"name": "country", "type": "string"}]}
      #- http://localhost:8081/subjects/
      #- http://localhost:8081/subjects/Kisi/versions/1

    depends_on:
      - kafka-server-1
    networks:
      - kafka_network
      
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8080:8080 # Changed to avoid port clash with akhq
    depends_on:
      - kafka-server-1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9093
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - kafka_network
  
  nifi:
    image: apache/nifi:1.13.1
    container_name: nifi-docker
    ports:
      - "8082:8080"
    networks:
      - kafka_network

  postgre:
    image: postgres:13
    container_name: postgre
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

